### ISSUE TITLE
Upgrade Synology WebStation // Container Manager

### ISSUE THREAD

**Issue by SylvainDx** [noiwid/tiko_heating_api#11]
Bonjour,

j'ai beau essayer j'ai l'impression de me casser le nez sur des évidences que je ne sais voir...
J'ai mis à jour mon Syno, le package WebStation a été complètement revu et les service web passent maintenant par un container...

Cela à modifié l'url d'appel du service.
J'ai mis à jour le chemin dans le tiko.env

et j'obtiens : 
```
Warning: Undefined array key "enr_ok" in /home/php/src/tiko.php on line 42

Warning: Undefined array key "hash" in /home/php/src/tiko.php on line 88

Warning: Undefined array key "install" in /home/php/src/tiko.php on line 88
```

en supprimant le fichier env, il me propose de saisir les info de mon compte mais j'ai au dessus : 
```
Warning: Undefined array key "enr_ok" in /home/php/src/tiko.php on line 42

Warning: Undefined variable $error_feedback in /home/php/src/tiko.php on line 845
```

par contre le fichier spyc.php est bien téléchargé (donc a priori droit d'écriture ok)
et le fichier env ne se créer pas.

je joins mon phpinfo pour le cas où...
[PHP 8.2.10 - phpinfo().pdf](https://github.com/noiwid/tiko_heating_api/files/12565280/PHP.8.2.10.-.phpinfo.pdf)

**Comment by noiwid** [comment]
Hello,
il faut que tu désactives sur la configuration de PHP l'affichage des
warning... en soit ces alertes ne sont pas bloquantes, mais elles empêchent
la page web de renvoyer du json valide à home assistant.

cette page semble expliquer comment faire sur synology:
https://kb.synology.com/en-au/DSM/help/WebStation/application_webserv_php?version=7

voir la partie : display_errors

**Comment by SylvainDx** [comment]
Merci beaucoup pour ton retour rapide et bien vu ! 
encore désolé de ces questions basiques ...
ça ronronne a nouveau.

Bon il n'y a pas trop besoin de chauffer en ce moment mais on moins on trace l'évolution des températures ^^
