### ISSUE TITLE
Je ne peux pas récupérer les info tiko

### ISSUE THREAD

**Issue by rapiglesia** [noiwid/tiko_heating_api#14]
Bonjour,

Depuis hier la remonter de données ne fonctionne plus. (ne marche plus depuis 23/01/2024 - 11:45)

Je me sert de l'api pour recuperer la temperatures des pieces de la maison avec la commande suivante:
curl -k -s 'https://ds220.local:6007/tiko.php?hash=***token***'
Depuis hier la commande remonte la valeur null.

J'ai tester d'autres commandes tel que:
curl -k -s 'https://ds220.local:6007/tiko.php?hash=***token***&consumption=true'
Qui elle me retourne la valeur de la consommation.

![tiko_issue](https://github.com/noiwid/tiko_heating_api/assets/53955181/569e26f6-8ad1-4be0-b18d-f833cf72d1a2)

Tester avec la version v1.5.5, v1.6.1 et php 7.2

**Comment by noiwid** [comment]
Bonjour,
Merci pour l'info, j'étais complètement passé à côté, et constate la même chose que toi.
L'API semble avoir légèrement évolué de leur côté, je viens de publier une v1.7 qui corrige le bug, peux tu me confirmer que c'est également ok pour toi ?

Les modifs sont dans cette section ;
 /**********************************
   * GET heaters datas + global modes
   ***********************************/

**Comment by rapiglesia** [comment]
C'est ok.
Merci pour la réactivité
