### ISSUE TITLE
Impossible de configurer

### ISSUE THREAD

**Issue by Tombost** [noiwid/tiko_heating_api#15]
Bonjour, j'avais la version 1.4 qui fonctionnais très bien
Depuis hier un bug est apparu et je ne pouvais plus rien récupérer.
J'ai donc récupérer la version 1.7
J'ai bien mon fichier .env avec mes crediential mais quand je requete https://monsite.fr/tiko/tiko.php?install=true&hash=MON_HASH
la page PHP me donne aucune info de tiko mais me demande de saisir mes identifiants TIKO, sauf que je l'ai déjà fait ...
Je ne vois pas ce que j'ai fait de mal
![Capture d'écran 2024-01-24 192435](https://github.com/noiwid/tiko_heating_api/assets/18288957/94bbfa31-08a2-4c5c-baa0-4ec310cf0e48)

**Comment by SylvainDx** [comment]
Salut ! 
Alors effectivement l'integration depuis HA était en croix.
J'ai fait comme Tombost. remplacer l'ancien php par le nouveau et même punition, la fichier ne permet pas d'accéder a la page de config avec le .env existant.
et l'integration HA n'est pas plus fonctionnelle.

Next step - tout supprimer et repartir de 0 avec la nouveau fichier

**Comment by noiwid** [comment]
j'ai du rater un truc, je regarde ça dans l'aprem 👌🏻

**Comment by SylvainDx** [comment]
dans ce cas il me génère un nouveau fichier .env avec un nouveau hash mais on boucle sur la page d'identification comme si rien n'était fait

**Comment by Tombost** [comment]
> dans ce cas il me génère un nouveau fichier .env avec un nouveau hash mais on boucle sur la page d'identification comme si rien n'était fait

Exactement pareil

**Comment by Tombost** [comment]
J'ai absolument rien fait et c'est retombé en marche, bizarre non ?

Je vois que chaque requête tiko.php me genère cette ligne dans mes logs : 
[29/Dec/2023:23:57:34 +0100] "GET /tiko/tiko.php?hash=xxx HTTP/1.1" 200 415 xxx.fr "-" "got (https://github.com/sindresorhus/got)" "-"

Est-ce qu'il y avait un problème avec ce "got" ?

**Comment by Tombost** [comment]
Ca ne fonctionne de nouveau plus depuis 4h ce matin.
Je vais essayer de comprendre pourquoi.

**Comment by Tombost** [comment]
J'ai peu être quelque chose
J'ai transformer ton code PHP pour réaliser les requêtes via Node-RED afin d'avoir un peu plus de DEBUG.
L'api TIKO est maintenant limité, j'ai au le message via Node-RED lors de mes tests : 
`message: "Rate limit reached. The rate for 'post:email' is '20/h'"`

Cela peut être une piste

**Comment by noiwid** [comment]
ahhhh, je comprends mieux pourquoi je ne parvenait pas à reproduire le bug
hier 😅

je vais voir si je ne peux pas loguer les messages de retour/erreur de leur
API dans H.A, ça permettrait d'y voir plus clair.

**Comment by Tombost** [comment]
Et c'est aussi limité à 100/jour
Je viens de recevoir le message.
Du coup je dois faire un rafraîchissement toute les 15 minutes au lieu de 5 auparavant.

**Comment by SylvainDx** [comment]
100 / jour ??Ça laisse peut de place pour les ordres et la programmation depuis HA.

Envoyé depuis Yahoo Mail pour Android 
 
  Le ven., janv. 26, 2024 à 18:09, ***@***.***> a écrit:   


Et c'est aussi limité à 100/jour
Je viens de recevoir le mail.
Du coup je dois faire un rafraîchissement toute les 15 minutes au lieu de 5 auparavant.

**Comment by Tombost** [comment]
> 100 / jour ??Ça laisse peut de place pour les ordres et la programmation depuis HA. Envoyé depuis Yahoo Mail pour Android Le ven., janv. 26, 2024 à 18:09, ***@***.***> a écrit: Et c'est aussi limité à 100/jour Je viens de recevoir le mail. Du coup je dois faire un rafraîchissement toute les 15 minutes au lieu de 5 auparavant. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Oui c'est très peu ça m'embête aussi dans mon utilisation...
