### ISSUE TITLE
Nouvelle installation

### ISSUE THREAD

**Issue by SylvainDx** [noiwid/tiko_heating_api#17]
Salut ! 

j'avais un pb sur mon instance HA depuis quelque temps.
J'en ai profité pour passer sur la dernière version 1.8

a la première exécution avec un moteur Php 7.4.33 on a une erreure ligne 892
`  		<?php}`
il manque a priori un espace : 
`  		<?php }`

J'avais mes valeurs qui remontait bien dans HA pas de soucis et en fin de journée tout est passé à 0

en consultant la page tiko.php?install=true&hash=...
j'ai comme retour : 
`{"error":"Limite de taux atteinte. Le taux pour post:email est 5\/m"}`

et maintenant j'ai même un : 
`{"error":"Limite de taux atteinte. Le taux pour post:email est 100\/d"}`

cela doit faire echo à la modification de l'api tiko dont il a été question cet hiver.
Mais la mes radiateurs sont a l'arrêt et je ne donne aucun ordre depuis HA. 

Ai-je raté un réglage quelque part ?

PS. hey ! en tentant la reconfiguration j'ai même débloqué le succès : 
`{"error":"Limite de taux atteinte. Le taux pour post:email est 20\/h"}`

**Comment by noiwid** [comment]
hello, merci pour ton retour, c'est ok ca marche désormais?

**Comment by CharlyBrok** [comment]
Bonjour,
il reste le manque d'espace ligne 892 :)

**Comment by SylvainDx** [comment]
Le froid est un vrai moteur pour travailler sur les chauffages :)

du coup on repart de 0 pour la Nième fois :p 
sans aucun appel préalable des fonctionnalités après remise en œuvre du package HA, ça fonctionne. (avec l'ajout de l'espace ligne 892)
reste à voir combien de temps l'api va continuer a donner des résultats ;)

**Comment by SylvainDx** [comment]
Bon au final vu que notre hôte en a fait autant, j'ai basculé sur https://github.com/marvinroger/hass-addon-tiko ;)
un Tiko2MQTT qui a l'air de bien fonctionner pour l'heure !

Merci encore @noiwid pour tout ton travail très efficace sur l'interface Tiko / HA !
