### ISSUE TITLE
Pré-requis : "allow_url_fopen = On" // Synology Web Sation DSM7

### ISSUE THREAD

**Issue by SylvainDx** [noiwid/tiko_heating_api#2]
Salut :)

j'ai rajouté des précisions dans le titre au cas où car je pense qu'on est dans du très spécifique ici 

ça coince au démarrage du coup :
![image](https://user-images.githubusercontent.com/88506082/223147938-b36535c2-3cfa-46b9-a86b-6f2b2c67aba4.png)

Alors que le phpinfo() renvoie bien 
![image](https://user-images.githubusercontent.com/88506082/223148552-b0e00141-cb0f-46f2-9f0f-8d67e3faf433.png)

**Comment by noiwid** [comment]
Tu peux commenter les lignes 765 à 769, qui posent le problème : 
```
        if(!file_get_contents('https://raw.githubusercontent.com/mustangostang/spyc/master/Spyc.php')){
            $error_feedback .= '<li><strong>Erreur :</strong> le paramètre <strong>allow_url_fopen</strong> n\'est pas activé. Veuillez vous assurez que la ligne suivantes est présente et non commentée dans votre fichier <strong>php.ini</strong>
             <div class="code">allow_url_fopen = On</div>
          </li>';
        }
```
Il y a visiblement autre chose qui empêche d'aller récupérer ce fichier via la fonction file_get_contents:
https://community.synology.com/enu/forum/17/post/25354

Dans ce cas, il faut que tu remettes en place le fichier spyc.php à la main.

Je vais modifier cette partie pour aller chercher le script via curl ;)

**Comment by noiwid** [comment]
Une nouvelle version 1.3 corrige le problème en récupérant le fichier spyc.php via une commande curl.

**Comment by SylvainDx** [comment]
J'ai repris de 0 avec la 1.3, ça fonctionne nickel !

Merci encore pour ta curiosité et ton support !

**Comment by noiwid** [comment]
Génial, merci pour ton retour 🙏
As-tu été obligé de customiser la variable $currentFolder à la main dans le script tiko.php, où le script a réussi à récupèrer automatiquement la valeur attendue?

**Comment by SylvainDx** [comment]
Je n'ai touché à rien ce coup ci 😉

Envoyé depuis Yahoo Mail pour Android 
 
  Le mer., mars 8, 2023 à 11:03, ***@***.***> a écrit:   


Génial, merci pour ton retour 🙏
As-tu été obligé de customiser la variable $currentFolder à la main dans le script tiko.php, où le script a réussi à récupèrer automatiquement la valeur attendue?
