### ISSUE TITLE
Capteurs d'humidité

### ISSUE THREAD

**Issue by SylvainDx** [noiwid/tiko_heating_api#3]
Bonjour Noiwid,

a la lecture du fichier Yaml généré, je m'aperçois qu'il est possible de récupérer l'indication d'humidité des capteurs.

j'ai rajouté cela dans le fichier pour chaque zone : 

      -
      platform: template
      sensors:
        salon_humidity:
          friendly_name: Salon Humidité
          value_template: "{{ state_attr('sensor.tiko_settings','salon_dry')}}"
          device_class: humidity

**Comment by noiwid** [comment]
Hello Sylvain,
Très bonne idée, bien que j'ai récupéré cette info par l'API et stockée dans H.A, je n'en faisait jusqu'ici pas grand chose !

J'ai intégré ta modif dans une nouvelle release v1.4.
Tu peux également rajouter **unit_of_measurement: %** sur chaque sensor.

Je viens de voir que les devs de _better-thermostat-ui-card_ prévoyaient de rajouter l'affichage de l'humidité sur leur carte, je vais attendre qu'ils déploient leur update pour intégrer l'info sur lovelace...

**Comment by SylvainDx** [comment]
On peut déjà l'intégrer si tu rajoute l'integration better-thermostat Mais ça fait tout recréer une seconde fois, et le comportement au changement de target est bizarre.
L'avantage à faire l'integration betterthermostat c'est qu'il supporte l'inversion des température cible et actuelle. Sans ça ça bug.

Pour l'unité j'avais tenté de l'ajouter mais HA n'avait pas voulu redémarrer avec 😅
