### ISSUE TITLE
Alerte HomeAssistant

### ISSUE THREAD

**Issue by SylvainDx** [noiwid/tiko_heating_api#4]
Bonjour,

Je viens de mettre à jour HA, et j'ai maintenant un avertissement dans la config concernant les fichier YAML et le positionnement des switch et sensor.

Sauf erreur de ma part je n'ai que l'integration Tiko qui se base ainsi sur des fichier Yaml.
nous serions donc a risque à partir de la 2023.8 à venir. ;)

<img width="349" alt="image" src="https://github.com/noiwid/tiko_heating_api/assets/88506082/811ae32d-1bca-494b-a174-5e2e53e9aef9">

**Comment by Najihel** [comment]
Fix on 49a6b7538f7ea5d6fa943586cd8ad9cd7b356695 I think =)

**Comment by noiwid** [comment]
Hello Sylvain, 
Najhel à bien vu, cette modification a été apportée à la version 1.5. 
On a plus de switch: au premier niveau de l'arbre, ils sont désormais sous les command_line: de mon côté plus aucun warning... 

Si tu en vois encore, elle viennent probablement d'un autre YAML que le mien...

**Comment by SylvainDx** [comment]
Ah mais c'est que je suis resté sur la v1 moi ^^
