### ISSUE TITLE
Page blanche et erreurs PHP

### ISSUE THREAD

**Issue by Maxou44** [noiwid/tiko_heating_api#9]
Bonjour,

J'essaye d'installer ce script sur un serveur en utilisant PHP-FPM 8.1 et nginx, j'ai réussi à le lancer une première fois j'ai eu un message d'erreur comme quoi curl n'était pas installé, j'ai installé curl et depuis j'ai juste une page blanche contenant du HTML et j'ai trouvé ces erreurs dans les logs :

[29-Jul-2023 14:15:14] WARNING: [pool www] child 174165 said into stderr: "NOTICE: PHP message: PHP Warning:  Undefined array key "enr_ok" in /var/www/html/tiko.php on line 42"
[29-Jul-2023 14:15:14] WARNING: [pool www] child 174165 said into stderr: "NOTICE: PHP message: PHP Warning:  Undefined variable $error_feedback in /var/www/html/tiko.php on line 845"

L'accès à la page déclenche bien le téléchargement du fichier spyc.php qui se met dans le bon dossier mais la page d'installation ne s'affiche pas

Une idée de la raison ? Pensez vous pouvoir fournir une image docker pour faciliter l'installation sur différent environements ?

Voici le contenu de la page HTML générée : 
```html
<!doctype html>
    <html lang="fr">
    <head>
      <meta charset="utf-8">
      <title>TIKO API Endpoint</title>
    </head>
    <body>
             <style>
           body { font-family:tahoma }
           label { display:inline-block; width:80px; text-align:right }
           .code { padding:4; margin: 4px 0; background-color:#EEE; font-family:courier }

           ol.border {
              list-style-type: none;
              list-style-type: decimal !ie;     
              margin: 0;
              margin-left: 3em;
              padding: 0;     
              counter-reset: li-counter;
          }

          ol.border > li{
              position: relative;
              margin-bottom: 20px;
              padding-left: 0.5em;
              min-height: 3em;
              border-left: 2px solid #CCCCCC;
          }

          ol.border > li:before {
              position: absolute;
              top: 0;
              left: -1em;
              width: 0.8em;     
              font-size: 3em;
              line-height: 1;
              font-weight: bold;
              text-align: right;
              color: #00796B; 
              content: counter(li-counter);
              counter-increment: li-counter;
          }
          </style>
      </body>
  </html>
```

**Comment by noiwid** [comment]
Bonjour,
votre php est visiblement paramètré en mode "développement", qui retourne
les Warning et notice, il faut éditer le fichier php.ini, et ne laisse que
E_ERROR sur la ligne error_reporting, puis redémarrer le serveur web.

Ensuite, pour comprendre la raison de la la page blanche, vous pouvez
decommenter la partie de mon code php liée au debug, et rafraîchir la page,
le message d'erreur devrait permettre d'y voir plus clair.

La partie commentée demarre part
/* et finir par /* il faut supprimer les /* et /*

ÉDIT:
je pense que votre problème vient du fait qu'une fois le fichier de config tiko.env crée, l'installation n'est plus accessible via la simple url du script, il faut rajouter le param &install=true, essayez de supprimer ce fichier tiko.env et relancer le script, avec Curl installé ça devrait désormais dérouler...


Le sam. 29 juil. 2023, 17:29, Maxime Baconnais ***@***.***> a
écrit :

**Comment by Maxou44** [comment]
Je viens de refaire quelques tests, en activant le morceau de code pour le debug je n'ai plus d'erreur sur la page mais je garde une page blanche. Le fichier tiko.env n'existe pas et n'est pas créé à l'éxecution du script. Même en passant le paramètre tiko.php?install=true dans l'url

**Comment by noiwid** [comment]
il semble que ton serveur web ne peut pas écrire de fichiers dans le
dossier qui héberge la page web.

est ce que la librairie spyc.php a pu être récupérée par curl (le fichier
devrait lui aussi être dans le dossier de ton tiko.php)?

Le sam. 29 juil. 2023, 23:49, Maxime Baconnais ***@***.***> a
écrit :

**Comment by Maxou44** [comment]
Le fichier spyc.php est bien présent, pas le tiko.env

**Comment by Maxou44** [comment]
Fixed in #10
